import 'package:flutter/material.dart';

class SetupText extends StatelessWidget {
  final String textKey;
  final TextStyle? style;
  final TextAlign? textAlign;
  final String languageCode;
  final double? fontSize;
  final FontWeight? fontWeight;
  final Color? color;

  const SetupText(
    this.textKey, {
    super.key,
    this.style,
    this.textAlign,
    this.languageCode = 'fa',
    this.fontSize,
    this.fontWeight,
    this.color,
  });

  static const Map<String, Map<String, String>> _localizedValues = {
    'fa': {
      'title': 'انتخاب زبان',
      'subtitle': 'لطفاً زبان مورد نظر خود را انتخاب نمایید',
      'btn_fa': 'فارسی',
      'btn_en': 'English',
      'btn_fr': 'Français',
      'continue': 'ادامه',
      'familiarity_title': 'نام شما',
      'hint_first_name': 'نام',
      'hint_last_name': 'نام خانوادگی',
      'err_lang': 'لطفاً زبان برنامه را انتخاب کنید.',
      'err_name': 'لطفاً نام و نام خانوادگی خود را وارد نمایید.',
      'gender_title': 'جنسیت شما',
      'gender_female': 'بانو',
      'gender_male': 'آقا',
      'err_gender': 'لطفاً جنسیت خود را مشخص کنید.',
      'age_title': 'سن شما',
      'err_age': 'لطفاً سن خود را وارد نمایید.',
      'age_subtitle': 'سن شما چقدر است؟',
      'physical_data_title': 'اطلاعات فیزیکی',
      'activity_title': 'سطح فعالیت بدنی',
      'weight_title': 'وزن (کیلوگرم)',
      'height_title': 'قد (سانتی‌متر)',
      'waist_title': 'دور کمر (سانتی‌متر)',
      'err_physical_data': 'لطفاً اطلاعات قد، وزن و دور کمر خود را تکمیل کنید.',
      'err_activity_level': 'لطفاً سطح فعالیت بدنی خود را انتخاب کنید.',
      'activity_sedentary': 'کم‌تحرک',
      'activity_light_very': 'بسیار سبک',
      'activity_light': 'متوسط',
      'activity_moderate': 'نسبتاً فعال',
      'activity_active': 'بسیار فعال',
      'activity_desc_sedentary':
          'کمتر از ۳۰ دقیقه فعالیت در هفته. اشتغال در مشاغل پشت میزنشین بدون فعالیت ورزشی منظم.',
      'activity_desc_light_very':
          '۱ تا ۳ ساعت فعالیت سبک در هفته، شامل پیاده‌روی ملایم روزانه یا تمرینات کششی.',
      'activity_desc_light':
          '۳ تا ۵ ساعت فعالیت منظم در هفته، شامل سه جلسه تمرین ورزشی یا پیاده‌روی تند.',
      'activity_desc_moderate':
          '۶ تا ۷ ساعت فعالیت ورزشی در هفته با تحرک بدنی قابل توجه.',
      'activity_desc_active':
          'تمرینات سنگین روزانه (۱.۵ تا ۲ ساعت)، شامل بدنسازی حرفه‌ای یا فعالیت‌های سنگین.',
      'activity_subtitle': 'میزان فعالیت بدنی خود را مشخص کنید.',
      'diet_title': 'رژیم غذایی',
      'diet_subtitle': 'نوع رژیم غذایی خود را انتخاب نمایید',
      'diet_omnivore': 'متعادل (همه چیز)',
      'diet_desc_omnivore':
          'مصرف انواع گروه‌های غذایی شامل گوشت، مرغ، ماهی و فرآورده‌های گیاهی بدون محدودیت.',
      'diet_vegetarian': 'گیاه‌خواری',
      'diet_desc_vegetarian':
          'عدم مصرف گوشت و مرغ، به همراه مصرف تخم‌مرغ و لبنیات.',
      'diet_vegan': 'وگان (گیاه‌خواری مطلق)',
      'diet_desc_vegan':
          'استفاده انحصاری از محصولات گیاهی بدون هیچ‌گونه فرآورده حیوانی.',
      'diet_keto': 'کتوژنیک',
      'diet_desc_keto': 'رژیم غذایی پرچربی و کم‌کربوهیدرات جهت مدیریت وزن.',
      'diet_low_carb': 'کم‌کربوهیدرات',
      'diet_desc_low_carb': 'کاهش میزان دریافت کربوهیدرات جهت تنظیم متابولیسم.',
      'err_diet_level': 'لطفاً نوع رژیم غذایی خود را تعیین کنید.',
      'restriction_title': 'حساسیت‌های غذایی',
      'restriction_subtitle':
          'حساسیت‌ها یا محدودیت‌های غذایی خود را مشخص کنید.',
      'err_restriction_level': 'لطفاً حساسیت‌های غذایی خود را انتخاب کنید.',
      'restrict_none': 'هیچ‌کدام',
      'restrict_dairy': 'لبنیات',
      'restrict_eggs': 'تخم‌مرغ',
      'restrict_nuts': 'آجیل',
      'restrict_gluten': 'گلوتن',
      'restrict_seafood': 'غذای دریایی',
      'restrict_soy': 'سویا',
      'restrict_sesame': 'کنجد',
      'restrict_peanuts': 'بادام‌زمینی',
      'restrict_wheat': 'گندم',
      'restrict_fish': 'ماهی',
      'restrict_shellfish': 'صدف و میگو',
      'restrict_mustard': 'خردل',
      'restrict_celery': 'کرفس',
      'restrict_sulfites': 'سولفیت',
      'restrict_lupin': 'ترمس',
      'restrict_corn': 'ذرت',
      'restrict_honey': 'عسل',
      'restrict_lactose': 'لاکتوز',
      'restrict_casein': 'کازئین',
      'restrict_almond': 'بادام',
      'restrict_hazelnut': 'فندق',
      'restrict_walnut': 'گردو',
      'restrict_cashew': 'بادام هندی',
      'restrict_pistachio': 'پسته',
      'restrict_brazil_nut': 'مغز برزیلی',
      'restrict_macadamia': 'ماکادمیا',
      'restrict_pecan': 'پکان',
      'restrict_coconut': 'نارگیل',
      'restrict_shrimp': 'میگو',
      'restrict_crab': 'خرچنگ',
      'restrict_lobster': 'لابستر',
      'restrict_oyster': 'صدف خوراکی',
      'restrict_clam': 'صدف دوکفه‌ای',
      'restrict_squid': 'مرکب',
      'restrict_tomato': 'گوجه‌فرنگی',
      'restrict_strawberry': 'توت‌فرنگی',
      'restrict_citrus': 'مرکبات',
      'restrict_kiwi': 'کیوی',
      'restrict_banana': 'موز',
      'restrict_avocado': 'آووکادو',
      'restrict_peach': 'هلو',
      'restrict_apple': 'سیب',
      'restrict_chocolate': 'شکلات',
      'restrict_cocoa': 'کاکائو',
      'restrict_coffee': 'قهوه',
      'restrict_caffeine': 'کافئین',
      'restrict_yeast': 'مخمر',
      'restrict_histamine': 'هیستامین',
      'restrict_fodmap': 'فودمپ',
      'restrict_fructose': 'فروکتوز',
      'restrict_histamine_rich': 'پرهیستامین',
      'restrict_garlic': 'سیر',
      'restrict_onion': 'پیاز',
      'restrict_pepper': 'فلفل',
      'restrict_chili': 'فلفل تند',
      'restrict_mushroom': 'قارچ',
      'restrict_legumes': 'حبوبات',
      'restrict_chickpea': 'نخود',
      'restrict_lentil': 'عدس',
      'restrict_bean': 'لوبیا',
      'restrict_pea': 'نخود فرنگی',
      'restrict_rice': 'برنج',
      'restrict_oat': 'جو دوسر',
      'restrict_barley': 'جو',
      'restrict_rye': 'چاودار',
      'restrict_buckwheat': 'گندم سیاه',
      'restrict_potato': 'سیب‌زمینی',
      'restrict_red_meat': 'گوشت قرمز',
      'restrict_pork': 'گوشت خوک',
      'restrict_beef': 'گوشت گاو',
      'restrict_chicken': 'مرغ',
      'restrict_egg_white': 'سفیده تخم‌مرغ',
      'restrict_egg_yolk': 'زرده تخم‌مرغ',
      'restrict_gelatin': 'ژلاتین',
      'restrict_msg': 'MSG',
      'restrict_aspartame': 'آسپارتام',
      'restrict_preservatives': 'نگهدارنده‌ها',
      'restrict_food_coloring': 'رنگ خوراکی',
      'restrict_sulfur': 'ترکیبات گوگردی',
      'restrict_alcohol': 'الکل',
      'restrict_vinegar': 'سرکه',
      'restrict_spice_mix': 'ادویه ترکیبی',
      'sleep_title': 'زمان خواب و بیداری',
      'sleep_subtitle': 'ساعات استراحت و خواب خود را مشخص کنید',
      'sleep_time_label': 'زمان خواب',
      'wake_time_label': 'زمان بیداری',
      'sleep_required_error':
          'لطفاً زمان خواب و زمان بیداری خود را انتخاب نمایید',
      'err_sleep': 'لطفاً زمان خواب و زمان بیداری خود را انتخاب نمایید',
    },
    'en': {
      'title': 'Select Language',
      'subtitle': 'Please select your preferred language',
      'btn_fa': 'Persian',
      'btn_en': 'English',
      'btn_fr': 'French',
      'continue': 'Continue',
      'familiarity_title': 'Your Name',
      'hint_first_name': 'First Name',
      'hint_last_name': 'Last Name',
      'err_lang': 'Please select a language.',
      'err_name': 'Please enter your full name.',
      'gender_title': 'Your Gender',
      'gender_female': 'Female',
      'gender_male': 'Male',
      'err_gender': 'Please specify your gender.',
      'age_title': 'Your Age',
      'err_age': 'Please enter your age.',
      'age_subtitle': 'What is your age?',
      'physical_data_title': 'Physical Information',
      'activity_title': 'Activity Level',
      'weight_title': 'Weight (kg)',
      'height_title': 'Height (cm)',
      'waist_title': 'Waist (cm)',
      'err_physical_data':
          'Please complete your height, weight, and waist measurements.',
      'err_activity_level': 'Please select your activity level.',
      'activity_sedentary': 'Sedentary',
      'activity_light_very': 'Very Light',
      'activity_light': 'Moderate',
      'activity_moderate': 'Moderately Active',
      'activity_active': 'Very Active',
      'activity_desc_sedentary':
          'Less than 30 mins/week. Desk job with no regular physical exercise.',
      'activity_desc_light_very':
          '1-3 hours/week of light activity, including daily walks or light stretching.',
      'activity_desc_light':
          '3-5 hours/week of regular exercise, including gym sessions or brisk walking.',
      'activity_desc_moderate': '6-7 hours/week of intense physical activity.',
      'activity_desc_active':
          'Heavy daily training (1.5-2 hours) including professional workouts.',
      'activity_subtitle': 'Select your physical activity level.',
      'diet_title': 'Diet Type',
      'diet_subtitle': 'Choose your dietary preference',
      'diet_omnivore': 'Omnivore',
      'diet_desc_omnivore':
          'Consuming all food groups including meat, poultry, fish, and plant products without restriction.',
      'diet_vegetarian': 'Vegetarian',
      'diet_desc_vegetarian':
          'Excluding meat and poultry, while consuming eggs and dairy products.',
      'diet_vegan': 'Vegan',
      'diet_desc_vegan':
          'Exclusively plant-based products without any animal-derived components.',
      'diet_keto': 'Ketogenic',
      'diet_desc_keto': 'High-fat, low-carb dietary approach.',
      'diet_low_carb': 'Low Carb',
      'diet_desc_low_carb':
          'Reduced carbohydrate intake for metabolic regulation.',
      'err_diet_level': 'Please select your diet type.',
      'restriction_title': 'Food Allergies',
      'restriction_subtitle': 'Specify your food allergies or restrictions.',
      'err_restriction_level': 'Please select your food allergies.',
      'restrict_none': 'None',
      'restrict_dairy': 'Dairy',
      'restrict_eggs': 'Eggs',
      'restrict_nuts': 'Nuts',
      'restrict_gluten': 'Gluten',
      'restrict_seafood': 'Seafood',
      'restrict_soy': 'Soy',
      'restrict_sesame': 'Sesame',
      'restrict_peanuts': 'Peanuts',
      'restrict_wheat': 'Wheat',
      'restrict_fish': 'Fish',
      'restrict_shellfish': 'Shellfish',
      'restrict_mustard': 'Mustard',
      'restrict_celery': 'Celery',
      'restrict_sulfites': 'Sulfites',
      'restrict_lupin': 'Lupin',
      'restrict_corn': 'Corn',
      'restrict_honey': 'Honey',
      'restrict_lactose': 'Lactose',
      'restrict_casein': 'Casein',
      'restrict_almond': 'Almond',
      'restrict_hazelnut': 'Hazelnut',
      'restrict_walnut': 'Walnut',
      'restrict_cashew': 'Cashew',
      'restrict_pistachio': 'Pistachio',
      'restrict_brazil_nut': 'Brazil nut',
      'restrict_macadamia': 'Macadamia',
      'restrict_pecan': 'Pecan',
      'restrict_coconut': 'Coconut',
      'restrict_shrimp': 'Shrimp',
      'restrict_crab': 'Crab',
      'restrict_lobster': 'Lobster',
      'restrict_oyster': 'Oyster',
      'restrict_clam': 'Clam',
      'restrict_squid': 'Squid',
      'restrict_tomato': 'Tomato',
      'restrict_strawberry': 'Strawberry',
      'restrict_citrus': 'Citrus',
      'restrict_kiwi': 'Kiwi',
      'restrict_banana': 'Banana',
      'restrict_avocado': 'Avocado',
      'restrict_peach': 'Peach',
      'restrict_apple': 'Apple',
      'restrict_chocolate': 'Chocolate',
      'restrict_cocoa': 'Cocoa',
      'restrict_coffee': 'Coffee',
      'restrict_caffeine': 'Caffeine',
      'restrict_yeast': 'Yeast',
      'restrict_histamine': 'Histamine',
      'restrict_fodmap': 'FODMAP',
      'restrict_fructose': 'Fructose',
      'restrict_histamine_rich': 'Histamine-rich',
      'restrict_garlic': 'Garlic',
      'restrict_onion': 'Onion',
      'restrict_pepper': 'Pepper',
      'restrict_chili': 'Chili',
      'restrict_mushroom': 'Mushroom',
      'restrict_legumes': 'Legumes',
      'restrict_chickpea': 'Chickpea',
      'restrict_lentil': 'Lentil',
      'restrict_bean': 'Beans',
      'restrict_pea': 'Peas',
      'restrict_rice': 'Rice',
      'restrict_oat': 'Oat',
      'restrict_barley': 'Barley',
      'restrict_rye': 'Rye',
      'restrict_buckwheat': 'Buckwheat',
      'restrict_potato': 'Potato',
      'restrict_red_meat': 'Red meat',
      'restrict_pork': 'Pork',
      'restrict_beef': 'Beef',
      'restrict_chicken': 'Chicken',
      'restrict_egg_white': 'Egg white',
      'restrict_egg_yolk': 'Egg yolk',
      'restrict_gelatin': 'Gelatin',
      'restrict_msg': 'MSG',
      'restrict_aspartame': 'Aspartame',
      'restrict_preservatives': 'Preservatives',
      'restrict_food_coloring': 'Food coloring',
      'restrict_sulfur': 'Sulfur compounds',
      'restrict_alcohol': 'Alcohol',
      'restrict_vinegar': 'Vinegar',
      'restrict_spice_mix': 'Mixed spices',
      'sleep_title': 'Sleep & Wake Time',
      'sleep_subtitle': 'Configure your resting and sleeping hours',
      'sleep_time_label': 'Sleep time',
      'wake_time_label': 'Wake time',
      'sleep_required_error': 'Please select your sleep and wake times',
      'err_sleep': 'Please select your sleep and wake times',
    },
    'fr': {
      'title': 'Choisir la langue',
      'subtitle': 'Veuillez sélectionner votre langue',
      'btn_fa': 'Persan',
      'btn_en': 'Anglais',
      'btn_fr': 'Français',
      'continue': 'Continuer',
      'familiarity_title': 'Votre Nom',
      'hint_first_name': 'Prénom',
      'hint_last_name': 'Nom de famille',
      'err_lang': 'Veuillez sélectionner une langue.',
      'err_name': 'Veuillez entrer votre nom complet.',
      'gender_title': 'Votre Genre',
      'gender_female': 'Femme',
      'gender_male': 'Homme',
      'err_gender': 'Veuillez spécifier votre genre.',
      'age_title': 'Votre Âge',
      'err_age': 'Veuillez entrer votre âge.',
      'age_subtitle': 'Quel est votre âge ?',
      'physical_data_title': 'Informations Physiques',
      'activity_title': 'Niveau d’activité',
      'weight_title': 'Poids (kg)',
      'height_title': 'Taille (cm)',
      'waist_title': 'Tour de taille (cm)',
      'err_physical_data':
          'Veuillez compléter vos mesures de taille, poids et tour de taille.',
      'err_activity_level': 'Veuillez sélectionner votre niveau d’activité.',
      'activity_sedentary': 'Sédentaire',
      'activity_light_very': 'Très léger',
      'activity_light': 'Modéré',
      'activity_moderate': 'Modérément actif',
      'activity_active': 'Très actif',
      'activity_desc_sedentary':
          'Moins de 30 min/semaine. Travail de bureau sans exercice physique régulier.',
      'activity_desc_light_very':
          '1-3 h/semaine d’activité légère, incluant des promenades quotidiennes.',
      'activity_desc_light':
          '3-5 h/semaine d’exercice régulier, incluant des séances en salle de sport.',
      'activity_desc_moderate': '6-7 h/semaine d’activité physique intense.',
      'activity_desc_active':
          'Entraînement quotidien intense (1.5 à 2 heures).',
      'activity_subtitle': 'Sélectionnez votre niveau d’activité physique.',
      'diet_title': 'Type de Régime',
      'diet_subtitle': 'Choisissez votre préférence alimentaire',
      'diet_omnivore': 'Omnivore',
      'diet_desc_omnivore':
          'Consommation de tous les groupes d’aliments sans restriction.',
      'diet_vegetarian': 'Végétarien',
      'diet_desc_vegetarian':
          'Sans viande ni volaille, avec œufs et produits laitiers.',
      'diet_vegan': 'Vegan',
      'diet_desc_vegan': 'Produits exclusivement d’origine végétale.',
      'diet_keto': 'Cétogène',
      'diet_desc_keto': 'Régime riche en graisses et pauvre en glucides.',
      'diet_low_carb': 'Pauvre en Glucides',
      'diet_desc_low_carb': 'Apport réduit en glucides.',
      'err_diet_level': 'Veuillez sélectionner votre type de régime.',
      'restriction_title': 'Allergies Alimentaires',
      'restriction_subtitle':
          'Veuillez indiquer vos allergies ou restrictions alimentaires.',
      'err_restriction_level':
          'Veuillez sélectionner vos allergies alimentaires.',
      'restrict_none': 'Aucun',
      'restrict_dairy': 'Produits laitiers',
      'restrict_eggs': 'Œufs',
      'restrict_nuts': 'Fruits à coque',
      'restrict_gluten': 'Gluten',
      'restrict_seafood': 'Fruits de mer',
      'restrict_soy': 'Soja',
      'restrict_sesame': 'Sésame',
      'restrict_peanuts': 'Arachides',
      'restrict_wheat': 'Blé',
      'restrict_fish': 'Poisson',
      'restrict_shellfish': 'Crustacés',
      'restrict_mustard': 'Moutarde',
      'restrict_celery': 'Céleri',
      'restrict_sulfites': 'Sulfites',
      'restrict_lupin': 'Lupin',
      'restrict_corn': 'Maïs',
      'restrict_honey': 'Miel',
      'restrict_lactose': 'Lactose',
      'restrict_casein': 'Caséine',
      'restrict_almond': 'Amande',
      'restrict_hazelnut': 'Noisette',
      'restrict_walnut': 'Noix',
      'restrict_cashew': 'Cajou',
      'restrict_pistachio': 'Pistache',
      'restrict_brazil_nut': 'Noix du Brésil',
      'restrict_macadamia': 'Macadamia',
      'restrict_pecan': 'Pécan',
      'restrict_coconut': 'Noix de coco',
      'restrict_shrimp': 'Crevette',
      'restrict_crab': 'Crabe',
      'restrict_lobster': 'Homard',
      'restrict_oyster': 'Huître',
      'restrict_clam': 'Palourde',
      'restrict_squid': 'Calamar',
      'restrict_tomato': 'Tomate',
      'restrict_strawberry': 'Fraise',
      'restrict_citrus': 'Agrumes',
      'restrict_kiwi': 'Kiwi',
      'restrict_banana': 'Banane',
      'restrict_avocado': 'Avocat',
      'restrict_peach': 'Pêche',
      'restrict_apple': 'Pomme',
      'restrict_chocolate': 'Chocolat',
      'restrict_cocoa': 'Cacao',
      'restrict_coffee': 'Café',
      'restrict_caffeine': 'Caféine',
      'restrict_yeast': 'Levure',
      'restrict_histamine': 'Histamine',
      'restrict_fodmap': 'FODMAP',
      'restrict_fructose': 'Fructose',
      'restrict_histamine_rich': 'Riche en histamine',
      'restrict_garlic': 'Ail',
      'restrict_onion': 'Oignon',
      'restrict_pepper': 'Poivre',
      'restrict_chili': 'Piment',
      'restrict_mushroom': 'Champignon',
      'restrict_legumes': 'Légumineuses',
      'restrict_chickpea': 'Pois chiche',
      'restrict_lentil': 'Lentille',
      'restrict_bean': 'Haricots',
      'restrict_pea': 'Petits pois',
      'restrict_rice': 'Riz',
      'restrict_oat': 'Avoine',
      'restrict_barley': 'Orge',
      'restrict_rye': 'Seigle',
      'restrict_buckwheat': 'Sarrasin',
      'restrict_potato': 'Pomme de terre',
      'restrict_red_meat': 'Viande rouge',
      'restrict_pork': 'Porc',
      'restrict_beef': 'Bœuf',
      'restrict_chicken': 'Poulet',
      'restrict_egg_white': 'Blanc d\'œuf',
      'restrict_egg_yolk': 'Jaune d\'œuf',
      'restrict_gelatin': 'Gélatine',
      'restrict_msg': 'MSG',
      'restrict_aspartame': 'Aspartame',
      'restrict_preservatives': 'Conservateurs',
      'restrict_food_coloring': 'Colorants',
      'restrict_sulfur': 'Composés soufrés',
      'restrict_alcohol': 'Alcool',
      'restrict_vinegar': 'Vinaigre',
      'restrict_spice_mix': 'Épices mélangées',
      'sleep_title': 'Temps de sommeil et de réveil',
      'sleep_subtitle': 'Configurez vos heures de repos et de sommeil',
      'sleep_time_label': 'Heure de sommeil',
      'wake_time_label': 'Heure de réveil',
      'sleep_required_error':
          'Veuillez sélectionner votre heure de sommeil et votre heure de réveil',
      'err_sleep':
          'Veuillez sélectionner votre heure de sommeil et votre heure de réveil',
    },
  };

  static String getString(String languageCode, String key) {
    final langMap = _localizedValues[languageCode] ?? _localizedValues['fa']!;
    return langMap[key] ?? key;
  }

  @override
  Widget build(BuildContext context) {
    final resolvedText = getString(languageCode, textKey);

    // ترکیب استایل‌ها اگر پارامترهای مستقیم داده شده باشند
    final effectiveStyle = style?.copyWith(
          fontSize: fontSize ?? style?.fontSize,
          fontWeight: fontWeight ?? style?.fontWeight,
          color: color ?? style?.color,
        ) ??
        TextStyle(
          fontSize: fontSize,
          fontWeight: fontWeight,
          color: color,
        );

    return Text(
      resolvedText,
      style: effectiveStyle.fontSize == null &&
              effectiveStyle.color == null &&
              effectiveStyle.fontWeight == null &&
              style == null
          ? null
          : effectiveStyle,
      textAlign: textAlign,
    );
  }
}
